apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    project: amazon
  tolerations:
  - key: "project"
    operator: "Equal"
    value: "amazon"
    effect: "NoExecute"